import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

import archiver from 'archiver';

function ensure(...p){ fs.mkdirSync(p.join('/'), { recursive: true }); return p.join('/'); }

function writeCover(outDir, projectName){
  const md = `# ${projectName || 'Project'} Design Package\n\nGenerated by ULTIDA.\n\n## Rooms\n${(() => { const roomsDir = path.join(outDir, 'rooms'); if (!fs.existsSync(roomsDir)) return '- none'; return fs.readdirSync(roomsDir).map(r => `- ${r}`).join('\n'); })()}\n\n## Outputs\n- 3D renders: JPEG/JPG\n- 3D models: SKP\n- Elevations: DXF + PDF\n`;
  fs.writeFileSync(path.join(outDir, 'PACKAGE.md'), md);
}

export async function buildDeliveryPackage({ projectId, projectName, label } = {}){
  const projectRoot = path.resolve(__dirname, '..', '..');
  const id = String(projectId || 'project').replace(/[^a-z0-9-]+/gi, '_').toLowerCase();
  const outRoot = ensure(projectRoot, '_deliverables', id);
  const packageDir = ensure(outRoot, 'packages', label || 'latest');
  const zipPath = path.join(packageDir, `ULTIDA_${id}_${label || 'latest'}.zip`);

  writeCover(outRoot, projectName);

  const output = fs.createWriteStream(zipPath);
  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.pipe(output);

  const addDir = (dir, base = outRoot) => {
    if (!fs.existsSync(dir)) return;
    fs.readdirSync(dir).forEach(f => {
      const fp = path.join(dir, f);
      const rel = path.relative(base, fp);
      if (fs.statSync(fp).isDirectory()) return addDir(fp, base);
      archive.file(fp, { name: rel });
    });
  };

  addDir(path.join(outRoot, 'rooms'));
  ['INDEX.md', 'PACKAGE.md'].forEach(f => {
    const fp = path.join(outRoot, f);
    if (fs.existsSync(fp)) archive.file(fp, { name: f });
  });

  await archive.finalize();
  return new Promise((resolve, reject) => {
    output.on('close', () => resolve(zipPath));
    output.on('error', reject);
  });
}
