export declare const USER_ROLES: readonly ["admin", "owner", "designer", "sales_designer", "estimator", "production_manager", "site_exec", "client_viewer"];
export type UserRole = (typeof USER_ROLES)[number];
export declare const PROJECT_STAGES: readonly ["draft", "lead_qualified", "intake_in_progress", "intake_complete", "site_capture", "plan_analysis_review", "scene_ready", "design_in_progress", "render_review", "proposal_review", "client_approval_pending", "design_approved", "production_preparation", "production_ready", "delivered"];
export type ProjectStage = (typeof PROJECT_STAGES)[number];
export declare const PROJECT_STATUSES: readonly ["active", "on_hold", "completed", "archived"];
export type ProjectStatus = (typeof PROJECT_STATUSES)[number];
export declare const BUDGET_BANDS: readonly ["economy", "standard", "premium", "luxury", "ultra_luxury_bespoke"];
export type BudgetBand = (typeof BUDGET_BANDS)[number];
export declare const ROOM_TYPES: readonly ["foyer", "living_room", "dining_room", "kitchen", "utility", "master_bedroom", "bedroom", "kids_bedroom", "guest_bedroom", "study", "balcony", "bathroom", "powder_room", "mandir_room", "passage", "office_cabin", "workstation_area", "reception", "showroom_zone"];
export type RoomType = (typeof ROOM_TYPES)[number];
export declare const MODULE_TYPES: readonly ["kitchen_base_run", "kitchen_wall_run", "kitchen_tall_unit", "kitchen_sink_unit", "kitchen_hob_unit", "kitchen_island", "wardrobe_swing", "wardrobe_sliding", "loft_storage", "tv_unit", "feature_wall_panel_system", "mandir_floor_unit", "mandir_wall_unit", "crockery_unit", "study_desk", "shoe_rack", "vanity_unit", "utility_storage", "false_ceiling_system"];
export type ModuleType = (typeof MODULE_TYPES)[number];
export declare const SCENE_BRANCHES: readonly ["main"];
export type SceneBranch = string;
export declare const RENDER_TIERS: readonly ["draft", "review", "final"];
export type RenderTier = (typeof RENDER_TIERS)[number];
export declare const APPROVAL_STATUS: readonly ["pending", "shortlisted", "approved", "rejected"];
export type ApprovalStatus = (typeof APPROVAL_STATUS)[number];
export declare const DRAWING_TYPES: readonly ["floor_plan", "elevation", "ceiling_plan", "schedule_sheet", "section"];
export type DrawingType = (typeof DRAWING_TYPES)[number];
export declare const RULE_SEVERITIES: readonly ["hard", "soft", "advisory", "score"];
export type RuleSeverity = (typeof RULE_SEVERITIES)[number];
export declare const RULE_STATUSES: readonly ["pass", "warn", "fail"];
export type RuleStatus = (typeof RULE_STATUSES)[number];
export declare const ESTIMATE_TYPES: readonly ["rough", "budget_fit", "concept", "boq_quote", "final_quote", "variation_quote"];
export type EstimateType = (typeof ESTIMATE_TYPES)[number];
export declare const ESTIMATE_STATUSES: readonly ["draft", "shared", "revised", "approved", "rejected", "superseded"];
export type EstimateStatus = (typeof ESTIMATE_STATUSES)[number];
export declare const INVOICE_TYPES: readonly ["proforma", "advance", "milestone", "tax", "final", "credit_note", "debit_note"];
export type InvoiceType = (typeof INVOICE_TYPES)[number];
export declare const INVOICE_STATUSES: readonly ["draft", "issued", "partially_paid", "paid", "overdue", "void"];
export type InvoiceStatus = (typeof INVOICE_STATUSES)[number];
export declare const PAYMENT_METHODS: readonly ["bank_transfer", "cheque", "cash", "card", "upi", "emi_partner", "finance_partner", "other"];
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];
export declare const PAYMENT_STATUSES: readonly ["recorded", "cleared", "bounced", "reversed", "refunded"];
export type PaymentStatus = (typeof PAYMENT_STATUSES)[number];
export declare const VARIATION_STATUSES: readonly ["proposed", "priced", "awaiting_client_approval", "approved", "rejected", "executed", "canceled"];
export type VariationStatus = (typeof VARIATION_STATUSES)[number];
export declare const PURCHASE_ORDER_STATUSES: readonly ["draft", "approved", "issued", "partially_received", "fully_received", "closed", "canceled"];
export type PurchaseOrderStatus = (typeof PURCHASE_ORDER_STATUSES)[number];
export declare const JOB_STATUSES: readonly ["queued", "running", "waiting_for_input", "succeeded", "failed", "canceled", "stale"];
export type JobStatus = (typeof JOB_STATUSES)[number];
export declare const JOB_TYPES: readonly ["floor_plan_interpretation", "floor_plan_review_package", "scene_shell_generation", "scene_validation", "pricing_generation", "render_generation", "drawing_generation", "proposal_export", "bom_generation", "cutlist_generation", "deliverables_packaging", "similarity_indexing"];
export type JobType = (typeof JOB_TYPES)[number];
export type UUID = string;
export type ISODate = string;
export type ISODateTime = string;
